# Generated by Django 5.1.5 on 2025-03-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='academic_registrar',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'registrar'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrar_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
