# Generated by Django 5.1.5 on 2025-03-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_issues_academic_registrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_issues', to='my_app.course'),
        ),
    ]
