# Generated by Django 5.1.7 on 2025-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_type',
            field=models.CharField(choices=[('student_number', 'Student Number'), ('Lecturer_number', 'Lecturer Number'), ('Registrar_number', 'Registrar Number')], default='student_number', max_length=20),
        ),
    ]
