# Generated by Django 5.1.7 on 2025-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_customuser_number_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_number',
            new_name='number',
        ),
    ]
