# Generated by Django 5.1.5 on 2025-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_customuser_contact_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('assigned', 'Assigned')], default='pending', max_length=100),
        ),
    ]
