# Generated by Django 5.1.7 on 2025-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_student_number_customuser_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Lecturer_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Registrar_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
