# Generated by Django 5.1.7 on 2025-03-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_customuser_number_customuser_lecturer_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number_type',
            new_name='Number_type',
        ),
    ]
