# Generated by Django 5.1.5 on 2025-03-15 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_issues_academic_registrar_alter_issues_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='academic_registrar',
            field=models.ForeignKey(limit_choices_to={'role': 'registrar'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrar_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issues',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_issues', to='my_app.course'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_issues', to='my_app.department'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
