# Generated by Django 5.1.7 on 2025-03-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_number_type_customuser_number_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Number_type',
            new_name='number_type',
        ),
    ]
