# Generated by Django 5.1.7 on 2025-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_number_type_customuser_number_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number_type',
            field=models.CharField(choices=[('student_number', 'Student Number'), ('lecturer_number', 'Lecturer Number'), ('registrar_number', 'Registrar Number')], default='student_number', max_length=20),
        ),
    ]
