# Generated by Django 5.1.7 on 2025-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_customuser_number_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Lecturer_number',
            field=models.CharField(default='30', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Registrar_number',
            field=models.CharField(default='40', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(default='24', max_length=10, unique=True),
        ),
    ]
