# Generated by Django 5.1.7 on 2025-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_customuser_lecturer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Lecturer_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Registrar_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
