# Generated by Django 5.1.6 on 2025-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number_type',
            field=models.CharField(choices=[('student_number', 'Student Number'), ('lecturer_number', 'Lecturer Number'), ('registrar_number', 'Registrar Number')], max_length=20),
        ),
    ]
