# Generated by Django 5.1.5 on 2025-04-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_customuser_number_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Lecturer_number',
            new_name='lecturer_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Registrar_number',
            new_name='registrar_number',
        ),
    ]
