# Generated by Django 5.1.6 on 2025-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_lecturer_number_customuser_lecturer_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='issue_type',
            new_name='complaint',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issues',
            name='complaint_type',
            field=models.CharField(choices=[('test', 'Test'), ('course work', 'Course work'), ('final exam', 'Final exam')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='custom_complaint',
            field=models.TextField(null=True),
        ),
    ]
