# Generated by Django 5.1.5 on 2025-04-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_rename_issue_type_issues_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], null=True),
        ),
    ]
