# Generated by Django 5.1.5 on 2025-04-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
