# Generated by Django 5.1.5 on 2025-04-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
